### ISSUE TITLE
Tooltip issue when more than 32 currencies

### ISSUE THREAD

**Issue by jeremiahbreeden** [Centias/BankItems#1]
So I found on toons that had more than 32 currencies (the size of a page of the currency bag in the UI) that the tooltips on currencies near the bottom of the actual in game currency tab would not show the current player's count or add it to the total.  I tracked this down and the fix is pretty simple, treat it like mail and AH

https://github.com/Centias/BankItems/blob/1bd39b5e17180db282d270856c6d6a6c14a22c5e/BankItems.lua#L6441

should be changed to:
```lua
if bagNum == 101 or bagNum == 102 or bagNum == 103 then
```

I already fixed this locally for myself, but figured you should know in case you wanted to fix your copy.   

NOTE: don't try and change the bag field .size to anything as it is capped for the actual UI page size of 32 and changing it causes LUA errors in some windows.  I tried it to see.  It looks like bags 104 and 105 defined a realSize field, which is also an option, but then you would need to add 102 to that ELSEIF branch instead and add a line to update that field in the respective function.  It just seemed easier to update the first part of the IF instead.

**Comment by jeremiahbreeden** [comment]
It also appears to still affect search results.  For example, on my paladin, I have lesser charms of good fortune, but it is after the first 32 currencies.  So when I type "bis lesser" it shows the counts for my other toons but no my paladin even though he has thousands.  I'm still trying to figure out how to fix search.

**Comment by Centias** [comment]
Thanks to your pointers in the first message, I was actually able to find a solution for the second part, because it was almost exactly the same thing. I'll roll it into an update here soon.
