### ISSUE TITLE
Fixed a few issues with old bagNum 4 to bagNum 5

### ISSUE THREAD

**Issue by bit-bash** [Centias/BankItems#10]
I made a few fixes that correct some tooltips where BI treated the reagent bag as the bank.
It would report items in my bank when they were actually in my reagent bag.
Differences based on release 10.0.2.5.
If this update is applied, one might have to open all their bags again on all characters to update the BI cache.

Summary:
line 3192 from:
`				if bagNum >4 and bagNum < 12 then --bank bags`
to:
`				if bagNum >= 6 and bagNum <= 12 then --bank bags`

line 3319 from:
`				if bagNum >4 and bagNum < 12 then --bank bags`
to:
`				if bagNum >= 6 and bagNum <= 12 then --bank bags`

line 4534 from:
`		for i = 0, 4 do`
to:
`		for i = BACKPACK_CONTAINER, NUM_TOTAL_EQUIPPED_BAG_SLOTS do`

[BankItems.lua.zip](https://github.com/Centias/BankItems/files/10310529/BankItems.lua.zip)

**Comment by Centias** [comment]
Rolled this into the project and made a new release.
