### ISSUE TITLE
Error with new update.

### ISSUE THREAD

**Issue by tommy610** [Centias/BankItems#11]
Getting errors when I mouse over items in my bag

20x BankItems/BankItems.lua:6667: attempt to perform arithmetic on local 'item' (a string value)
[string "@BankItems/BankItems.lua"]:6667: in function `BankItems_AddTooltipData'
[string "@BankItems/BankItems.lua"]:6612: in function <BankItems/BankItems.lua:6611>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@Blizzard_Communities/GuildNews.lua"]:167: in function <Blizzard_Communities/GuildNews.lua:153>
[string "=[C]"]: in function `CommunitiesGuildNewsButton_OnEnter'
[string "*GuildNews.xml:67_OnEnter"]:2: in function <[string "*GuildNews.xml:67_OnEnter"]:1>

Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 AllTheThingsOnTooltipClearedHook = true
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:340
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:299
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:334
 shownMoneyFrames = 1
 AttachComplete = true
 AllTheThingsProcessing = "|cffa335ee|Hitem:1

**Comment by Centias** [comment]
Can you include what items were triggering this? I can't seem to make the error get thrown.

**Comment by Centias** [comment]
I see a couple mentions of "AllTheThings" which I know is another addon, but I've never used it. Seems like there might be some interference between the two.

**Comment by tommy610** [comment]
It seems the error has not come back, probably with the recent update. But the error would show up when ever I mouse over item in my bag that I can in my bank, mostly reagents

**Comment by tommy610** [comment]
Ok I lie. the error still comes back and it seems to pop up on items that have ranks on them, mostly dragonflight items. Also the funny thing is these errors only show up on my laptop and not my desktop, when both have the same addons and ui setup. Maybe i just need to delete the saved lua file for bankitems?

**Comment by Centias** [comment]
Maybe make a backup of the addon(s) and saved variables, reinstall, see if things get sorted out. I'm not sure what would be different between the two, or why this would throw an error. 'item' is getting set to the itemID of whatever is opening the tooltip, and I've never seen one be a non-integer.

**Comment by tommy610** [comment]
I tried deleting the addon and the saved lua file and reinstall the addon, and the error still pops up. I even tried using the saved lua files from my desktop and copy it over to the laptop, since my desktop wasn't giving errors, and still giving me the error. Such a weird error to only happen on my laptop. Oh wells.

**Comment by Centias** [comment]
If you feel comfortable with doing a little test, if you go to BankItems.lua and find the line right before the one with the error (6667) and add a quick "print(item)" and reload, you can make it print whatever the itemID is supposed to be for that item. I feel like something somewhere has to be messing with it and causing weird results, but I have no idea what it's coming up with.

**Comment by tommy610** [comment]
![image](https://user-images.githubusercontent.com/117709534/216163255-deac0f13-ff01-497d-b2b7-d3f786c17b80.png)

All item print looks normal except for this one

**Comment by Centias** [comment]
print(item) is printing out all of these as item:###### ? That seems odd. I have the complete opposite and they all look like this:
![image](https://user-images.githubusercontent.com/62023588/216191028-6d967889-849f-4a7f-a8ed-0493fe97965d.png)

That probably explains why you're getting errors, but then the next question is why are your items getting returned in this format.

**Comment by tommy610** [comment]
Oh so when I said I didn't get errors on my desktop, that was a lie. I just had the error sound disabled. But yeah not sure why it would show differently, maybe another addon doing it. I'll try to go through each addon and see if that is the case

**Comment by Centias** [comment]
I have no idea why they are coming out as item:#####, but right after this line at 6648 
	`local item = BankItems_createUniqueItem(link) or item`
you could try adding in this line
	`item = gsub(item, "item:", "")`
	
It should strip out the "item:" part and leave just the number, but I don't know how the rest of it will behave because it seems like the items must be getting stored as "item:####" for some reason. You could check for this in the SavedVariables file to see how they are getting stored.

**Comment by tommy610** [comment]
yup all the items are stored like this...

				["link"] = "|cff1eff00|Hitem:200287::::::::45:105:::::::::|h[Iskaara Tuskarr Insignia]|h|r",
				["hasLoot"] = false,
				["iconFileID"] = 4687629,
				["stackCount"] = 5,
				["isReadable"] = false,
				["hasNoValue"] = true,
				["isLocked"] = false,
				["itemID"] = 200287,
				["isBound"] = true,
				["hyperlink"] = "|cff1eff00|Hitem:200287::::::::45:105:::::::::|h[Iskaara Tuskarr Insignia]|h|r",
				["isFiltered"] = false,
				["count"] = 5,
				["quality"] = 2,

**Comment by Centias** [comment]
But that actually looks relatively normal. Link / hyperlink is the string that if put in the chat in-game creates a link you can click to see the item. itemID here is just a number.

**Comment by tommy610** [comment]
Sorry for the slow responses. but I've finally got around to adding "item = gsub(item, "item:", "")" and it seems to be working. No errors as of yet. If anything pops up I'll let you know. Thank you!

**Comment by tommy610** [comment]
Now this error comes up with that change and it seems to pop up with I mouse over any jc gem with rankings on them

17x BankItems/BankItems.lua:6668: attempt to perform arithmetic on local 'item' (a string value)
[string "@BankItems/BankItems.lua"]:6668: in function `BankItems_AddTooltipData'
[string "@BankItems/BankItems.lua"]:6612: in function <BankItems/BankItems.lua:6611>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:936: in function `RefreshData'
[string "@FrameXML/GameTooltip.lua"]:502: in function <FrameXML/GameTooltip.lua:491>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 AllTheThingsOnTooltipClearedHook = true
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ClearBackdrop = <function> defined =[C]:-1
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:340
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:299
 shownMoneyFrames = 1
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 info = <table> {
 }
 SetUnit = <function> defined =[C]:-1
 AttachComplete = true
 AllTheThingsProcessing = "|cffa335ee|Hitem:192983::::::::70:73::13:1:3524:2:40:240:38:1:::::|h[Fierce Illimited Diamond |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]|h|r"
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:440
 SetVoidWithdrawalItem = <function> defined @In

**Comment by Centias** [comment]
What does 'item' end up being in this case? I don't have any cut Illimited Diamonds, but I have some other cut gems, and they seem fine. I'm not really sure what this "AllTheThingsProcessing" is about. Even with that addon enabled I don't get this error.

**Comment by tommy610** [comment]
![image](https://user-images.githubusercontent.com/117709534/219289789-9e5e16b9-45b6-4fa3-8cdd-f5fbe91b13f4.png)

**Comment by Centias** [comment]
For some reason it's grabbing the whole item link instead of just the item ID.
I'll have to see this weekend if I can find the right way to strip it down to just the base item ID, since what is there right now is apparently not working all the time.

**Comment by Centias** [comment]
Try replacing 
`item = gsub(item, "item:", "")`
with 
`_, item = strsplit(":", item)`

This doesn't seem to interfere with how things were functioning for me normally, but it should hopefully strip out the "item:" and all the other numbers that come after the next ":" leaving only the item number.

**Comment by tommy610** [comment]
Finally got around to trying this and so far no errors as of yet. Will keep you updated if anything. Thank you!
