### ISSUE TITLE
no currency amounts

### ISSUE THREAD

**Issue by Kimab** [Centias/BankItems#13]
hey there! 
just installed bankitems again and fixed errors i get with the solution described in issue#11. works good!
but now i discovered: applying the #11 'deactivates' the currency amounts are appearently completely gone! i miss them <3

thanks for your work

**Comment by Centias** [comment]
Hm, right you are. Not sure when I'll figure out a fix for the other thing that doesn't break this, but at least I'm seeing the problem too, so it's easier to test on.

**Comment by Kimab** [comment]
thanks for your help :) 
here is a new error:

1x BankItems/BankItems.lua:7030: '<eof>' expected near 'end'
Locals:

stopped working completely with this error

**Comment by Centias** [comment]
Is this only happening with a specific item or currency? Or happening with basically anything? I have it in my live file right now and haven't seen the error come up, so I'm not sure what's up.

**Comment by Kimab** [comment]
just found the what was going on!
idk why but for me its line 6648 and not 6649.
changed 6648 and works perfectly now! thanks alot

**Comment by Centias** [comment]
Hm, not sure why the line number is different. Maybe I have some extra line I added testing something else. Guess I should have included what the line was before just to make it clear what to replace. Glad you figured it out, though.
