### ISSUE TITLE
Ranks Showing Now, But Nothing Else Is

### ISSUE THREAD

**Issue by Lixialitixa** [Centias/BankItems#15]
I was looking forward to the most recent update for the different ranks of items to show. However, that's the ONLY thing that's showing in the mouseovers. If it's not an item that has a rank, it's not showing who else has it, or even if you have more than one.

I love this addon and I'm addicted to it! Yes, I made an account just so I could submit this issue.

**Comment by Centias** [comment]
So you aren't seeing the breakdown like this for basic items like potions?
![image](https://user-images.githubusercontent.com/62023588/234721586-5e3b14f1-44cc-4ca8-b557-ffdf6c6b2528.png)

**Comment by Centias** [comment]
So it's both
A ) not showing for items with no quality/rank
and B ) not showing the current character in the list at all?

I'm not really sure where to start troubleshooting this. If it's generating the tooltips for items with different qualities, it has to at least be getting the item ID. If it has that, it should be getting the rest too. But it sounds like for some reason something is going wrong in getting the current character's saved info for anything else, then just shows nothing. 

Are you getting any kind of error messages? I would basically expect some kind of error about ' BankItems_SelfCache '

**Comment by Centias** [comment]
Oh hey, what do you know. I guess I've had data saved the whole time and didn't realize it wouldn't "create" that slot when saving character data for the first time.

Looks like I had +2 where I needed a +1. Changing this line 
`for bagNum = ITEM_INVENTORY_BANK_BAG_OFFSET+2, ITEM_INVENTORY_BANK_BAG_OFFSET+1+NUM_BANKBAGSLOTS do
`

to this 
`for bagNum = ITEM_INVENTORY_BANK_BAG_OFFSET+1, ITEM_INVENTORY_BANK_BAG_OFFSET+1+NUM_BANKBAGSLOTS do
`

will fix the issue. I'll put out an actual update when I'm done with dungeons for the night.
