### ISSUE TITLE
Cross-Realm Searching (was an issue pre-patch too)

### ISSUE THREAD

**Issue by Lixialitixa** [Centias/BankItems#19]
Cross-realm searching no longer works. I've tried different settings and nothing seems to affect it. It does still work with connected realms. Note that this was an issue pre-patch also.

**Comment by Centias** [comment]
I'll have to see if I can figure it out over the weekend. I don't really play on many different servers, only connected ones, so I hadn't noticed.

**Comment by Centias** [comment]
Packing up an update to go out now.
