### ISSUE TITLE
Resilient Leather count

### ISSUE THREAD

**Issue by FireAllianceNX** [Centias/BankItems#23]
Hi! I have another item that isn't mashing together.
Resilient Leather 1 star will show with 1 and 3 stars when mouseover
Resilient Leather 2 star will show with 2 and 3 stars when mouseover
and 3 star will show with 2 and 3 stars.

**Comment by Centias** [comment]
You are correct. Should be an easy enough fix like the others.

**Comment by FireAllianceNX** [comment]
I'll try to do an eye test on all the base mats I have on all the professions so I'm not creating so many tickets. 🤞

**Comment by Centias** [comment]
Good catch. Added that to my code, I just have to publish an update later.

**Comment by Centias** [comment]
Published the release to fix these.
