### ISSUE TITLE
Faction integration

### ISSUE THREAD

**Issue by bbleeker** [Centias/BankItems#29]
Thanks for making this great addon! Now that you can mail items from one faction to the other, would it be possible to make BI count items from both factions, instead of ignoring the number of items my Alliance characters have when I'm on a Horde character and vice versa?

**Comment by Centias** [comment]
I forgot to reply to this, but there is a small checkbox on the main window for this. Opposite faction characters will show up in the tooltips with asterisks by their name.

The checkbox below it may also be useful with trading between realms becoming less restricted.

![image](https://github.com/user-attachments/assets/781562d0-a903-411f-8467-d167f7b95ebe)

**Comment by bbleeker** [comment]
Thank you very much! <3
