### ISSUE TITLE
Compatibility with WowUp

### ISSUE THREAD

**Issue by mortenn** [Centias/BankItems#3]
First off, thanks for fixing this addon for DragonIsles, I really missed it :)

I tried installing this addon using WowUp, and it did get added to the list in WowUp , but the version is displayed as 0.0.0 and the folder did not get created in the games Addons folder.
I ended up extracting the zip manually and that worked fine.

I'm not sure what went wrong with this, and WowUp doesn't supply any good developer docs it seems.

I'm using WowUp v2.9.2-beta.5 CF

**Comment by GTSavvy** [comment]
The [wowup example addon](https://github.com/WowUp/WowUp.Addon/releases/tag/1.0.15) makes the release package contents be in a folder at the top level, which BankItems currently doesnt do. I wonder if that is the reason...

**Comment by mortenn** [comment]
makes sense

**Comment by Centias** [comment]
I'm still kind of fumbling my way through making things work for at least the WowUp install, but I think I got it showing the proper version and installing the folder correctly now. I just re-installed my live addon through WowUp and it looks fine. Let me know how it turns out for you.

**Comment by GTSavvy** [comment]
I can now update through wowup using the github link and it installs and versions correctly

**Comment by mortenn** [comment]
This seems to be resolved, thanks!
