### ISSUE TITLE
TWW Pre-Patch Error "InterfaceOptions_AddCategory"

### ISSUE THREAD

**Issue by FireAllianceNX** [Centias/BankItems#31]
Happy Patch Day! I'm sure you have seen it already if you logged in, here's that error...

5x BankItems/BankItems.lua:8800: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@BankItems/BankItems.lua"]:8800: in main chunk

Locals:
bankPlayer = nil
bankPlayerName = nil
selfPlayer = nil
selfPlayerName = nil
selfPlayerRealmName = nil
selfPlayerRealmNormalized = nil
isBankOpen = false
isVoidReadable = false
isGuildBankOpen = false
dontUpdateClosedBank = false
pages = <table> {
 ReagentBank = 1
 AH = 1
 Void = 1
 Mail = 1
 Currency = 1
}
voidPageSize = 18
reagentBankPageSize = 28
BankItems_Quantity = 1
bagsToUpdate = <table> {
}
bankSlotsToUpdate = <table> {
}
mailItem = <table> {
}
sortedKeys = <table> {
}
sortedDelUserKeys = <table> {
}
sortedDelGuildKeys = <table> {
}
sortedGuildKeys = <table> {
}
selfPlayerConRealms = <table> {
}
realmNormalizer = <table> {
}
info = <table> {
}
CurrencyStringCache = <table> {
}
BankItemsMouseover = nil
BankItemsCFrames = <table> {
 bagsShown = 0
 bags = <table> {
 }
}
slotAdjust = <table> {
 104 = <table> {
 }
 105 = <table> {
 }
}
filterSearchText = ""
TOC = 110000
MAX_GUILDBANK_TABS = 8
L = <table> {
 BankItems Bindings = "BankItems Bindings"
 BANKITEMS_CAUTION_TEXT_2 = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"
 BANKITEMS_CAUTION_TEXT = "CAUTION: Some items were not parsed/displayed in this report because they do not exist in your WoW local cache yet. A recent WoW patch or launcher update caused the local cache to be cleared. Log on this character and visit the bank to correct this OR hover your mouse on every item in every bag to query the server for each itemlink (this may disconnect you).
"
 Toggle BankItems and all Bags = "Toggle BankItems and all Bags"
 Search guild banks = "Search guild banks"
 BankItems Options = "BankItems Options"
 Open currencies bag = "Open currencies bag"
 Open auction house bag = "Open auction house bag"
 Show only exact item matches in tooltip counts = "Show only exact item matches in tooltip counts"
 Delete a Character: = "Delete a Character:"
 Search mailbox = "Search mailbox"
 Open guild bank = "Open guild bank"
 Include the following guild banks: = "Include the following guild banks:"
 Toggle BankItems Guild Bank = "Toggle BankItems Guild Bank"
 Show extra item tooltip information = "Show extra item tooltip information"
 Toggle BankItems and all Bank Bags = "Toggle BankItems and all Bank Bags"
 Open BankItems bags with Blizzard bags = "Open BankItems bags with Blizzard bags"
 Lock main window from being moved = "Lock main window from being moved"
 Search bank and bank bags = "Search bank and bank bags"
 Open mail bag = "Open mail bag"
 Delete a Guild: = "Delete a Guild:"
 Sort Ascending = "Sort Ascending"
 Toggle BankItems = "Toggle BankItems"
 On the command "/bi": = "On the command "/bi":"
 Open BankItems with Blizzard windows = "Open BankItems with Blizzard windows"
 Open void storage bag = "Open void storage bag"
 Search equipped gear = "Search equipped gear"
 Open bank bags = "Open bank bags"
 Sort data broker gold tooltip in ascending order = "Sort data broker gold tooltip in ascending order"
 Show reagent bank contents in a bag = "Show reagent bank contents in a bag"
 Open equipped items bag = "Open equipped items bag"
 Show Mail Call on Login = "Show Mail Call on Login"
 Search inventory bags = "Search inventory bags"
 Show character gold in total gold tooltip = "Show character gold in total gold tooltip"
 Open inventory bags = "Open inventory bags"
 Show void storage contents in a bag = "Show void storage contents in a bag"
 of = "of"
  of  = " of "
 Open reagent bank = "Open reagent bank"
 Show the minimap button = "Show the minimap button"
}
BANKITEMS_VERSION = 10000302
BANKITEMS_VERSIONTEXT = "BankItems v10.0.3.2"
BANKITEMS_BOTTOM_SCREEN_LIMIT = 80
BANKITEMS_UCFA = nil
BAGNUMBERS = <table> {
 1 = 0
 2 = 1
 3 = 2
 4 = 3
 5 = 4
 6 = 5
 7 = 6
 8 = 7
 9 = 8
 10 = 9
 11 = 10
 12 = 11
 13 = 12
 14 = 100
 15 = 101
 16 = 102
 17 = 103
 18 = 104
 19 = 105
}
NUM_REAGENTBANKGENERIC_SLOTS = 98
VOID_STORAGE_MAX = 80
VOID_STORAGE_PAGES = 2
BANKITEMS_UIPANELWIN

**Comment by madar2252** [comment]
yea
well, with warband bank, I guess every bank addons life will be more complicated

**Comment by lostdrewid** [comment]
especially since warband banks are broken currently, so who knows *what* is going on behind the scenes with bank addons and whether they can function.

that said, I'm looking at the code... I never learned to code in lua but I *do* have a couple of very rusty decades in programming, and the formatting BankItems uses to add a panel to Options is not the same code as other addons use.  so this one might actually be something that can be fixed.

**Comment by lostdrewid** [comment]
woof.  I looked through other addons' codes for how they add to the options tab and only one used the same method as BankItems, *but that code worked* where BankItems' didn't, so I'm going back to believing this is a bank-addons-are-broken-currently thing.

I did comment out the offending line (listed below) and as long as you don't need to, you know, actually change any options, you're fine!  It's a temporary work around at best, but at least you won't get an error through casual use.

	-- InterfaceOptions_AddCategory(BankItems_OptionsFrame)

**Comment by Swarfimus** [comment]
@Centias Hi.  Thanks for whatever that is you did there, and I hope so much that I don't give any offense to say this, but that isn't helpful to me for what I need.  The only thing of use to me is the feature to mouse over items in my bags and have it show me in the tooltip how many of that item, if any, that I and/or my alts have in the bank.

**Comment by Centias** [comment]
That and the search are the next part I'm working on. They're coming soon.

**Comment by vttale** [comment]
Will you bundle up a release for the fixes you have already made?

Also, any thoughts on publishing updates on CurseForge?

**Comment by jgleigh** [comment]
> woof. I looked through other addons' codes for how they add to the options tab and only one used the same method as BankItems, _but that code worked_ where BankItems' didn't, so I'm going back to believing this is a bank-addons-are-broken-currently thing.
> 
> I did comment out the offending line (listed below) and as long as you don't need to, you know, actually change any options, you're fine! It's a temporary work around at best, but at least you won't get an error through casual use.
> 
> ```
> -- InterfaceOptions_AddCategory(BankItems_OptionsFrame)
> ```

I had to migrate my AddOns to the new Settings API.

https://warcraft.wiki.gg/wiki/Patch_10.0.0/API_changes

**Comment by jgleigh** [comment]
2x BankItems/BankItems.lua:1738: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@BankItems/BankItems.lua"]:1738: in function <BankItems/BankItems.lua:1737>

Needs to migrate to: Settings.OpenToCategory()

**Comment by Mike160770** [comment]
Ok - sorry for being a dumbass, but what do I have to do for getting this addon running? Thx

**Comment by Centias** [comment]
I was closer than I thought. Had to get back on the Beta to check, but tooltips for Warband should be working, and searching should be working. Also added in the fixes for the Options button. I tend to just click my way through the base game options to get there so I hadn't noticed.

Going to batch up a release. Let me know if there are other problems.
