### ISSUE TITLE
An error occurred while viewing the quest.

### ISSUE THREAD

**Issue by rucak78** [Centias/BankItems#33]
An error occurred in version 11.01 after the patch.

1x [ADDON_ACTION_BLOCKED] 애드온 'BankItems'|1이;가; 보호된 함수 'Frame:SetPropagateMouseClicks()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>

[string "=[C]"]: in function `SetPropagateMouseClicks'

[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:459: in function `UpdateMousePropagation'

[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:464: in function `OnAcquired'

[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:553: in function `OnAcquired'

[string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:52: in function `OnAcquired'

[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:207: in function `AcquirePin'

[string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:35: in function `RefreshAllData'

[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:474: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:473>

[string "=[C]"]: in function `secureexecuterange'

[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:477: in function `RefreshAllDataProviders'

[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:504: in function `RefreshAll'

[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:87: in function `OnShow'

[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:307: in function 
<...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:304>

[string "=[C]"]: ?

[string "=[C]"]: in function `Show'

[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:866: in function `ShowUIPanel'

[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'

[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'

[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:503: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:502>

[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by rucak78** [comment]
> 1x [ADDON_ACTION_BLOCKED] 애드온 'BankItems'|1이;가; 보호된 함수 'Frame:SetPropagateMouseClicks()' 호출을 시도했습니다. [string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485> [string "=[C]"]: in function `SetPropagateMouseClicks' [string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:459: in function `UpdateMousePropagation' [string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:464: in function `OnAcquired' [string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:553: in function `OnAcquired' [string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:52: in function `OnAcquired' [string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:207: in function `AcquirePin' [string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:35: in function `RefreshAllData' [string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:474: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:473> [string "=[C]"]: in function `secureexecuterange' [string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:477: in function `RefreshAllDataProviders' [string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:504: in function `RefreshAll' [string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:87: in function `OnShow' [string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:307: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:304> [string "=[C]"]: ? [string "=[C]"]: in function `Show' [string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:866: in function `ShowUIPanel' [string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState' [string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf' [string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:503: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:502> [string "=[C]"]: in function `ToggleWorldMap' [string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>
> 
> Locals: _ = Frame { } event = "ADDON_ACTION_BLOCKED" events =
> 
> {
> }

**Comment by Centias** [comment]
I haven't run into an error like this yet myself, and other than the mention of BankItems at the very beginning, I don't know how much this has to do with BankItems. It really doesn't have anything to do with the world map other than item tooltips. I can't even find anything in the code related to SetPropagateMouseClicks.

Has this happened again since? What was the quest that triggered this?

**Comment by rucak78** [comment]
Blizzard Error
World map error, no more errors
It occurred in the quest window itself.
Thank you for your confirmation
