### ISSUE TITLE
Duplicate "Total" values in tooltips

### ISSUE THREAD

**Issue by jere-software** [Centias/BankItems#34]
https://github.com/Centias/BankItems/blob/69d7ff11b8b8162d204a7b322e75b30aef49640c/BankItems.lua#L7859-L7861

These lines now duplicate newly added:

https://github.com/Centias/BankItems/blob/69d7ff11b8b8162d204a7b322e75b30aef49640c/BankItems.lua#L7952-L7954

Causing a duplicate `Total: xxxx` line in the tooltip.  I recommend removing one, though I don't know which is the correct one to remove.

**Comment by Centias** [comment]
Fixed this plus a couple other issues with the tooltips in v 11.0.0.2
