### ISSUE TITLE
Items equipped in profession slots not stored/counted

### ISSUE THREAD

**Issue by GTSavvy** [Centias/BankItems#8]
Items equipped in Profession slots do not get counted by Bank Items

![image](https://user-images.githubusercontent.com/119644994/208225864-2ab482a6-cc4a-4e8d-a719-5ca18f62b841.png)

but they are seen/counted if you move it into your bag.

![image](https://user-images.githubusercontent.com/119644994/208225888-4a76da8f-efa7-4308-8a29-39eab2b9b05d.png)

There is also no place to check these in the BankItems pane. Perhaps the "Equipped Items" (bag 100) should be updated to include them? 

Will probably need to check what kind of event occurs when these items are equipped/unequipped to make sure they get updated properly by the addon.

**Comment by Centias** [comment]
I noticed the same when I was trying to check if some needed to be upgraded, though I'm not sure what slots these are yet.

**Comment by Centias** [comment]
Turns out the slots for these are basically exactly what you would expect (20-28) and saved pretty easily.

**Comment by GTSavvy** [comment]
Confirmed that profession items show up in tooltip and BankItems window under "Equipped Items" now, but there's a bug. If you hover over an empty spot, it throws a lua error:

![image](https://user-images.githubusercontent.com/119644994/208251147-db754181-a7fa-4c1f-9f62-c67a3685ee80.png)

Seems we need to add these as inventory slots to BANKITEMS_INVSLOT:

https://wowpedia.fandom.com/wiki/InventorySlotId

Have a possible local fix, and working on a Pull Request for this.

**Comment by GTSavvy** [comment]
Merge request seems to work when hovering over empty profession slots now. Unsure if the extra unused fishing slots will be an issue in the future since the Equipped Item bag doesn't show enough slots for them.

![image](https://user-images.githubusercontent.com/119644994/208263132-3370de98-6527-4025-8cf9-7e25a529f58a.png)

I also didn't add the texture for the empty profession slots (like you can see on the empty shirt slot) so some other potential rooms to improve.

**Comment by Centias** [comment]
Good catch. I brought it in and replaced the zip file in the last release.
